### PR TITLE
hello

### PR DESCRIPTION
**Pull request by remtrik**

### CODE REVIEW

**Comment by n00b69** [comment]
@remtrik Why did you make battery status battery

**Comment by remtrik** [comment]
@n00b69 because i can do it

**Comment by n00b69** [comment]
Nuh uh lol, battery status > battery due to the fact battery obviously works but battery status is skibidi absent on a particular selection of devices (DO NOT TRUST SM8250 BATTERY DRIVERS)

**Comment by remtrik** [comment]
@n00b69 i do not fucking care approve my pr NOW

**Comment by n00b69** [comment]
How about make a pr for the brainrot guide and I will add you to contributors for your valuable future additions

**Pull request closed without merging**
